spring.datasource.url=jdbc:mariadb://localhost:3306/db_hospital_test?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.flyway.enabled=false